In [1]:
import numpy as np

In [18]:
x = [[1,2,3],[4,5,6],[7,8,9]]

In [13]:
y = np.array(x)

In [14]:
y #makes 2D array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
x = [[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]]

In [16]:
y = np.array(x)

In [17]:
y #3D array

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [27]:
np.array(x, dtype='int')

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
np.array(x, dtype='float')

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [29]:
np.array(x, dtype='complex')

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j],
       [7.+0.j, 8.+0.j, 9.+0.j]])

In [31]:
dt = np.dtype(np.int32)
print(dt)

int32


In [32]:
#Return a new array of given shape and type, filled with zeros.
np.zeros(2)

array([0., 0.])

In [36]:
np.zeros((3,3))
#to make a 2D array we have to pass dimension or size inside a tuple
# (rows,columns)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [37]:
np.zeros((3,2)) 

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [38]:
np.zeros((3,3)) + 5

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

In [39]:
np.zeros((3,3)) - 5

array([[-5., -5., -5.],
       [-5., -5., -5.],
       [-5., -5., -5.]])

In [40]:
np.zeros((3,3)) * 5

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [41]:
#Return a new array of given shape and type, filled with ones.
np.ones(3) 

array([1., 1., 1.])

In [42]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [47]:
#Return a 2-D array with ones on the diagonal and zeros elsewhere.
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [48]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [53]:
#like range in the lists
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [58]:
np.arange(3,10,2)

array([3, 5, 7, 9])

In [59]:
x = np.arange(10)

In [60]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [67]:
x.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [71]:
x.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [75]:
#Return evenly spaced numbers over a specified interval.
np.linspace(2,3,5)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [77]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [78]:
x.max()

9

In [79]:
x.min()

0

In [81]:
np.random.rand(3,5)

array([[0.76173674, 0.94705896, 0.01981788, 0.82923431, 0.74322484],
       [0.07460314, 0.40236422, 0.5820603 , 0.29581229, 0.74629571],
       [0.94691276, 0.69962218, 0.95975818, 0.9658108 , 0.85098922]])

In [83]:
np.random.randint(2,10,size=(3,5))

array([[3, 8, 2, 2, 3],
       [3, 2, 4, 3, 4],
       [3, 4, 5, 5, 9]])

In [85]:
np.random.randn(3,5)

array([[-1.13394482,  1.21940272, -1.766994  ,  0.85817393,  1.81768373],
       [-1.46722447, -1.33936815,  0.33682235, -0.22511933, -0.0512516 ],
       [-0.63810627,  0.28102693, -3.00231705,  1.24028533, -0.29101205]])

In [86]:
x = np.arange(0,21)

In [87]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [88]:
x[8]

8

In [89]:
x[12]

12

In [91]:
x[:10] #10 is not included

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [92]:
x[2:10] #starts from 2

array([2, 3, 4, 5, 6, 7, 8, 9])

In [94]:
x[2:10:3] #jump of 3

array([2, 5, 8])

In [95]:
x = np.arange(25).reshape(5,5)

In [96]:
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [98]:
#indexing in 2D array
#x[row,column]
x[2,2]

12

In [101]:
#for 22 4th row and 2nd column 
#(because row and columns starts from 0)
x[4,2]

22

In [102]:
#slicing in 2D array
x[0:2,2:5]

array([[2, 3, 4],
       [7, 8, 9]])

In [103]:
x[2:5,1:4]

array([[11, 12, 13],
       [16, 17, 18],
       [21, 22, 23]])

In [104]:
x = np.arange(20)

In [105]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [106]:
x[x>4]

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [107]:
x[x < 4]

array([0, 1, 2, 3])

In [108]:
#operations on numpy
x = np.arange(10)

In [109]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [110]:
y = np.arange(10,20)

In [111]:
y

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [113]:
z = x+y

In [115]:
z

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [116]:
z = x*y

In [117]:
z

array([  0,  11,  24,  39,  56,  75,  96, 119, 144, 171])

In [118]:
z = x/y

In [119]:
z

array([0.        , 0.09090909, 0.16666667, 0.23076923, 0.28571429,
       0.33333333, 0.375     , 0.41176471, 0.44444444, 0.47368421])

In [120]:
np.sin(x)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [121]:
np.cos(x)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026])

In [122]:
np.log2(y)

array([3.32192809, 3.45943162, 3.5849625 , 3.70043972, 3.80735492,
       3.9068906 , 4.        , 4.08746284, 4.169925  , 4.24792751])